workflows:
  ios-unsigned:
    name: Build Unsigned iOS IPA (Ionic)
    max_build_duration: 60
    environment:
      node: 20.19.0
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @ionic/cli
          npm ci
      - name: Ensure iOS platform
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          npm install @capacitor/ios
          npx cap sync ios
          
      - name: Build Ionic app
        script: |
          ionic build
          npx cap copy ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Create exportOptions.plist
        script: |
          cat <<EOF > ios/App/exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF
      - name: Build unsigned archive
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO
      - name: Export unsigned IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ipa \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
